enum TripTypes {
    TRIP_EDIT = "TRIP_EDIT",
    TRIP_ADD = "TRIP_ADD",
    TRIP_REMOVE = "TRIP_REMOVE",
    TRIP_ADD_FAVORITE = "TRIP_ADD_FAVORITE",
    TRIP_FETCH_LIST = "TRIP_FETCH_LIST",
    TRIP_REMOVE_FAVORITE = "TRIP_REMOVE_FAVORITE",
}

export default TripTypes;
