enum TripsTypes {
    TRIPS_EDIT = "TRIPS_EDIT",
    TRIPS_ADD = "TRIPS_ADD",
    TRIPS_REMOVE = "TRIPS_REMOVE",
    TRIPS_ADD_LIST = "TRIPS_ADD_LIST",
    TRIPS_SET_ACTIVE = "TRIPS_SET_ACTIVE",
    TRIPS_ERROR = "TRIPS_ERROR",
}

export default TripsTypes;
