enum TripsTypes {
    TRIPS_EDIT = "TRIPS_EDIT",
    TRIPS_ADD = "TRIPS_ADD",
    TRIPS_REMOVE = "TRIPS_REMOVE",
    TRIPS_ADD_FAVORITE = "TRIPS_ADD_FAVORITE",
    TRIPS_FETCH_LIST = "TRIPS_FETCH_LIST",
    TRIPS_REMOVE_FAVORITE = "TRIPS_REMOVE_FAVORITE",
}

export default TripsTypes;
