enum CountriesTypes {
    COUNTRIES_FETCHING = "COUNTRIES_FETCHING",
    COUNTRIES_FETCH_SUCCESS = "COUNTRIES_FETCH_SUCCESS",
    COUNTRIES_FETCH_ERROR = "COUNTRIES_FETCH_ERROR",
}

export default CountriesTypes;
